"""The plateau boards (brain, power, motion, clock): circuits validated
against the official symbols, placements without overlap, schematics that
kicad-cli can netlist. Routing is exercised on the smallest board only,
the others are regenerated by the runbook (minutes each)."""

import shutil
import subprocess
from pathlib import Path

import pytest
from analoggen.fplib import FOOTPRINT_DIR

pytestmark = pytest.mark.skipif(not FOOTPRINT_DIR.exists(), reason="KiCad libraries not installed")

BOARDS = ["brain", "power", "motion", "clock"]


def _module(name):
    import importlib

    return importlib.import_module(f"boardgen.{name}")


@pytest.mark.parametrize("name", BOARDS)
def test_circuit_and_placement(cfg, name):
    mod = _module(name)
    ckt = getattr(mod, f"build_{name}_circuit")(cfg)
    placements = getattr(mod, f"{name}_placements")(ckt)
    refs = [c.ref for c in ckt.components]
    assert len(refs) == len(set(refs))
    assert set(refs) == set(placements)
    spec = mod.SPEC
    for ref, (x, y, _rot) in placements.items():
        assert 0.0 < x < spec.width and 0.0 < y < spec.height, ref
    from boardgen.core import GenericBoard

    gb = GenericBoard(spec, ckt, placements)
    gb.place_all()  # raises on any courtyard overlap or part off the board
    groups = mod.schematic_groups()
    listed = {r for _t, _y, refs_ in groups for r in refs_}
    assert set(refs) <= listed, sorted(set(refs) - listed)


def test_brain_pins_come_from_the_yaml(cfg):
    from boardgen.brain import build_brain_circuit

    ckt = build_brain_circuit(cfg)
    u1 = next(c for c in ckt.components if c.ref == "U1")
    by_net = {net: num for num, net in u1.pins.items()}
    from analoggen.symlib import load_symbol

    sym = load_symbol("MCU_ST_STM32G4", "STM32G474RETx")
    names = {p.number: p.name for p in sym.pins}
    for signal, pin in cfg.plateau.brain.mcu_pins.items():
        assert names[by_net[signal]] == pin, signal
    assert names[by_net["BOOT0"]] == "PB8" and names[by_net["NRST"]] == "PG10"


def test_quadrant_links_mirror_the_quadrant_pinout(cfg):
    from boardgen.brain import build_brain_circuit

    ckt = build_brain_circuit(cfg)
    base = list(cfg.plateau.quadrant.link.pinout)
    for k in range(1, 5):
        j = next(c for c in ckt.components if c.ref == f"J{k}")
        nets = [j.pins[str(i + 1)] for i in range(16)]
        for a, b in zip(base, nets, strict=True):
            if a in ("AMP_OUT", "LED_DIN", "LED_DOUT"):
                continue
            assert a == b
        assert nets[3] == f"AMP_OUT{k}"


@pytest.mark.skipif(shutil.which("kicad-cli") is None, reason="kicad-cli not installed")
@pytest.mark.parametrize("name", BOARDS)
def test_schematic_netlists(cfg, name, tmp_path: Path):
    from analoggen.schematic import emit_schematic

    mod = _module(name)
    ckt = getattr(mod, f"build_{name}_circuit")(cfg)
    sch = tmp_path / f"{name}.kicad_sch"
    text = emit_schematic(ckt, name, groups=mod.schematic_groups(), project=name, paper="A1")
    sch.write_text(text, encoding="utf-8")
    out = tmp_path / "n.net"
    subprocess.run(
        ["kicad-cli", "sch", "export", "netlist", "--output", str(out), str(sch)],
        check=True,
        capture_output=True,
    )
    assert '(net (code "' in out.read_text(encoding="utf-8")


def test_motion_board_routes(cfg):
    from boardgen.motion import build_motion

    res = build_motion(cfg)
    assert res.clearance_errors == []
    assert len(res.open_nets) <= 2, res.open_nets
